# SPDX-Litense-Identifier:  MPL-2.0
from rdf_utils.namespace import (
    NS_MM_ACT,
    NS_MM_DISTRIB,
    NS_MM_DYN_COORD,
    NS_MM_DYN_ENT,
    NS_MM_EXEC,
    NS_MM_GEOM,
    NS_MM_GEOM_COORD,
    NS_MM_GEOM_REL,
    NS_MM_KC,
    NS_MM_KC_EXT,
    NS_MM_KC_STAT,
    NS_MM_QUDT,
    NS_MM_QUDT_QTY,
    NS_MM_QUDT_UNIT,
)

# Units
URI_QUDT_QK_MASS = NS_MM_QUDT_QTY["Mass"]
URI_QUDT_QK_LENGTH = NS_MM_QUDT_QTY["Length"]
URI_QUDT_QK_ANGLE = NS_MM_QUDT_QTY["Angle"]
URI_QUDT_QK_FORCE = NS_MM_QUDT_QTY["Force"]
URI_QUDT_QK_TORQUE = NS_MM_QUDT_QTY["Torque"]
URI_QUDT_QK_ANG_VEL = NS_MM_QUDT_QTY["AngularVelocity"]
URI_QUDT_QK_LIN_ACCEL = NS_MM_QUDT_QTY["LinearAcceleration"]
URI_QUDT_QK_FREQ = NS_MM_QUDT_QTY["Frequency"]

URI_QUDT_UNIT_RAD = NS_MM_QUDT_UNIT["RAD"]
URI_QUDT_UNIT_DEG = NS_MM_QUDT_UNIT["DEG"]
URI_QUDT_UNIT_KG = NS_MM_QUDT_UNIT["KiloGM"]
URI_QUDT_UNIT_G = NS_MM_QUDT_UNIT["GM"]
URI_QUDT_UNIT_KG_M2 = NS_MM_QUDT_UNIT["KiloGM-M2"]
URI_QUDT_UNIT_M = NS_MM_QUDT_UNIT["M"]
URI_QUDT_UNIT_CM = NS_MM_QUDT_UNIT["CentiM"]
URI_QUDT_UNIT_MM = NS_MM_QUDT_UNIT["MilliM"]

URI_QUDT_TYPE_QUANTITY = NS_MM_QUDT["Quantity"]

URI_QUDT_PRED_QUANTITY_KIND = NS_MM_QUDT["hasQuantityKind"]
URI_QUDT_PRED_UNIT = NS_MM_QUDT["unit"]
URI_QUDT_PRED_VALUE = NS_MM_QUDT["value"]

# Geometry
URI_GEOM_TYPE_POINT = NS_MM_GEOM["Point"]
URI_GEOM_TYPE_FRAME = NS_MM_GEOM["Frame"]
URI_GEOM_TYPE_VECTOR = NS_MM_GEOM["Vector"]
URI_GEOM_TYPE_BOUND_VECTOR = NS_MM_GEOM["BoundVector"]
URI_GEOM_TYPE_POSE = NS_MM_GEOM_REL["Pose"]
URI_GEOM_TYPE_POSITION = NS_MM_GEOM_REL["Position"]
URI_GEOM_TYPE_ORIENT = NS_MM_GEOM_REL["Orientation"]
URI_GEOM_TYPE_COLLINEAR = NS_MM_GEOM_REL["LineCollinearity"]
URI_GEOM_TYPE_POSITION_COORD = NS_MM_GEOM_COORD["PositionCoordinate"]
URI_GEOM_TYPE_POSITION_REF = NS_MM_GEOM_COORD["PositionReference"]
URI_GEOM_TYPE_ORIENT_COORD = NS_MM_GEOM_COORD["OrientationCoordinate"]
URI_GEOM_TYPE_ORIENT_REF = NS_MM_GEOM_COORD["OrientationReference"]
URI_GEOM_TYPE_POSE_COORD = NS_MM_GEOM_COORD["PoseCoordinate"]
URI_GEOM_TYPE_POSE_REF = NS_MM_GEOM_COORD["PoseReference"]
URI_GEOM_TYPE_VECTOR_XYZ = NS_MM_GEOM_COORD["VectorXYZ"]
URI_GEOM_TYPE_EULER_ANGLES = NS_MM_GEOM_COORD["EulerAngles"]
URI_GEOM_TYPE_DIRECTION_COSINE_XYZ = NS_MM_GEOM_COORD["DirectionCosineXYZ"]
URI_GEOM_TYPE_ANGLES_ABG = NS_MM_GEOM_COORD["AnglesAlphaBetaGamma"]
URI_GEOM_TYPE_EXTRINSIC = NS_MM_GEOM_COORD["Extrinsic"]
URI_GEOM_TYPE_INTRINSIC = NS_MM_GEOM_COORD["Intrinsic"]
URI_GEOM_TYPE_QUATERNION = NS_MM_GEOM_COORD["Quaternion"]
URI_GEOM_TYPE_SIMPLICIAL_COMPLEX = NS_MM_GEOM["SimplicialComplex"]
URI_GEOM_TYPE_RIGID_BODY = NS_MM_GEOM["RigidBody"]
URI_GEOM_TYPE_KTREE = NS_MM_GEOM["KinematicTree"]
URI_GEOM_TYPE_KGRAPH = NS_MM_GEOM["KinematicGraph"]

URI_GEOM_PRED_ORIGIN = NS_MM_GEOM["origin"]
URI_GEOM_PRED_SIMPLICES = NS_MM_GEOM["simplices"]
URI_GEOM_PRED_START = NS_MM_GEOM["start"]
URI_GEOM_PRED_VECT_X = NS_MM_GEOM["vector-x"]
URI_GEOM_PRED_VECT_Y = NS_MM_GEOM["vector-y"]
URI_GEOM_PRED_VECT_Z = NS_MM_GEOM["vector-z"]
URI_GEOM_PRED_OF = NS_MM_GEOM_REL["of"]
URI_GEOM_PRED_WRT = NS_MM_GEOM_REL["with-respect-to"]
URI_GEOM_PRED_LINES = NS_MM_GEOM_REL["lines"]
URI_GEOM_PRED_SEEN_BY = NS_MM_GEOM_COORD["as-seen-by"]
URI_GEOM_PRED_OF_POSE = NS_MM_GEOM_COORD["of-pose"]
URI_GEOM_PRED_OF_POSITION = NS_MM_GEOM_COORD["of-position"]
URI_GEOM_PRED_OF_ORIENT = NS_MM_GEOM_COORD["of-orientation"]
URI_GEOM_PRED_X = NS_MM_GEOM_COORD["x"]
URI_GEOM_PRED_Y = NS_MM_GEOM_COORD["y"]
URI_GEOM_PRED_Z = NS_MM_GEOM_COORD["z"]
URI_GEOM_PRED_AXES_SEQ = NS_MM_GEOM_COORD["axes-sequence"]
URI_GEOM_PRED_ALPHA = NS_MM_GEOM_COORD["alpha"]
URI_GEOM_PRED_BETA = NS_MM_GEOM_COORD["beta"]
URI_GEOM_PRED_GAMMA = NS_MM_GEOM_COORD["gamma"]
URI_GEOM_PRED_DIRECTION_COSINE_X = NS_MM_GEOM_COORD["direction-cosine-x"]
URI_GEOM_PRED_DIRECTION_COSINE_Y = NS_MM_GEOM_COORD["direction-cosine-y"]
URI_GEOM_PRED_DIRECTION_COSINE_Z = NS_MM_GEOM_COORD["direction-cosine-z"]

# Kinematic Chain
URI_KC_TYPE_KC = NS_MM_KC["KinematicChain"]
URI_KC_TYPE_SERIAL = NS_MM_KC["SerialComposition"]
URI_KC_TYPE_JOINT = NS_MM_KC["Joint"]
URI_KC_TYPE_REVOLUTE_JOINT = NS_MM_KC["RevoluteJoint"]
URI_KC_TYPE_REVOLUTE_JOINT_ORIENTED_AXIS = NS_MM_KC[
    "RevoluteJointWithOrientedAxisOfRotation"
]
URI_KC_PRED_JOINTS = NS_MM_KC["joints"]
URI_KC_PRED_BETWEEN_ATTACHMENTS = NS_MM_KC["between-attachments"]
URI_KC_PRED_COMMON_AXIS = NS_MM_KC["common-axis"]
URI_KC_PRED_ORIGIN_OFFSET = NS_MM_KC["origin-offset"]
URI_KC_STAT_JNT_POSITION = NS_MM_KC_STAT["JointPosition"]
URI_KC_STAT_JNT_VEL = NS_MM_KC_STAT["JointVelocity"]
URI_KC_STAT_JNT_FORCE = NS_MM_KC_STAT["JointForce"]
URI_KC_EXT_TYPE_JOINT_COUPLING = NS_MM_KC_EXT["JointCoupling"]
URI_KC_EXT_TYPE_SCLERONOMIC = NS_MM_KC_EXT["Scleronomic"]
URI_KC_EXT_PRED_INDEPENDENT_JOINT = NS_MM_KC_EXT["independent-joint"]
URI_KC_EXT_PRED_DEPENDENT_JOINT = NS_MM_KC_EXT["dependent-joint"]
URI_KC_EXT_PRED_MULTIPLIER = NS_MM_KC_EXT["multiplier"]
URI_KC_EXT_PRED_OFFSET = NS_MM_KC_EXT["offset"]
URI_KC_EXT_PRED_ROOT = NS_MM_KC_EXT["root"]
URI_KC_EXT_PRED_TIP = NS_MM_KC_EXT["tip"]

# Dynamics
URI_DYN_TYPE_RIGID_BODY_INERTIA = NS_MM_DYN_ENT["RigidBodyInertia"]
URI_DYN_TYPE_INERTIA_REFERENCE = NS_MM_DYN_COORD["InertiaReference"]
URI_DYN_TYPE_RIGID_BODY_INERTIA_COORD = NS_MM_DYN_COORD["RigidBodyInertiaCoordinate"]
URI_DYN_TYPE_MASS_SCALAR = NS_MM_DYN_COORD["MassScalar"]
URI_DYN_TYPE_MOMENT_OF_INERTIA_XYZ = NS_MM_DYN_COORD["MomentOfInertiaXYZ"]
URI_DYN_TYPE_PRODUCT_OF_INERTIA_XYZ = NS_MM_DYN_COORD["ProductOfInertiaXYZ"]

URI_DYN_PRED_OF_BODY = NS_MM_DYN_ENT["of-body"]
URI_DYN_PRED_ABOUT = NS_MM_DYN_ENT["about"]
URI_DYN_PRED_OF_INERTIA = NS_MM_DYN_COORD["of-inertia"]
URI_DYN_PRED_AS_SEEN_BY = NS_MM_DYN_COORD["as-seen-by"]
URI_DYN_PRED_MASS = NS_MM_DYN_COORD["mass"]
URI_DYN_PRED_IXX = NS_MM_DYN_COORD["ixx"]
URI_DYN_PRED_IXY = NS_MM_DYN_COORD["ixy"]
URI_DYN_PRED_IXZ = NS_MM_DYN_COORD["ixz"]
URI_DYN_PRED_IYY = NS_MM_DYN_COORD["iyy"]
URI_DYN_PRED_IYZ = NS_MM_DYN_COORD["iyz"]
URI_DYN_PRED_IZZ = NS_MM_DYN_COORD["izz"]

# Actuation
URI_ACT_TYPE_ACTUATION = NS_MM_ACT["Actuation"]
URI_ACT_PRED_JOINT = NS_MM_ACT["joint"]
URI_ACT_PRED_GEAR_RATIO = NS_MM_ACT["gear-ratio"]
URI_ACT_PRED_COMMAND_INTERFACE = NS_MM_ACT["command-interface"]
URI_ACT_PRED_STATE_INTERFACE = NS_MM_ACT["state-interface"]
URI_ACT_TYPE_JOINT_CURRENT = NS_MM_ACT["JointCurrent"]

# Distribution
URI_DISTRIB_TYPE_DISTRIB = NS_MM_DISTRIB["Distribution"]
URI_DISTRIB_PRED_DIM = NS_MM_DISTRIB["dimension"]

URI_DISTRIB_TYPE_CONT = NS_MM_DISTRIB["Continuous"]
URI_DISTRIB_TYPE_DISCR = NS_MM_DISTRIB["Discrete"]

URI_DISTRIB_TYPE_UNIFORM = NS_MM_DISTRIB["Uniform"]
URI_DISTRIB_PRED_UPPER = NS_MM_DISTRIB["upper-bound"]
URI_DISTRIB_PRED_LOWER = NS_MM_DISTRIB["lower-bound"]

URI_DISTRIB_TYPE_NORMAL = NS_MM_DISTRIB["Normal"]
URI_DISTRIB_PRED_MEAN = NS_MM_DISTRIB["mean"]
URI_DISTRIB_PRED_STD = NS_MM_DISTRIB["standard-deviation"]
URI_DISTRIB_PRED_COV = NS_MM_DISTRIB["covariance"]

URI_DISTRIB_TYPE_UNIFORM_ROT = NS_MM_DISTRIB["UniformRotation"]

URI_DISTRIB_TYPE_SAMPLED_QUANTITY = NS_MM_DISTRIB["SampledQuantity"]
URI_DISTRIB_PRED_FROM_DISTRIB = NS_MM_DISTRIB["from-distribution"]

# Execution Context
URI_EXEC_TYPE_SYS_RES = NS_MM_EXEC["SystemResource"]
URI_EXEC_TYPE_RES_PATH = NS_MM_EXEC["ResourceWithPath"]
URI_EXEC_TYPE_SCENE_INST = NS_MM_EXEC["SceneInstance"]
URI_EXEC_TYPE_SCENE_MODEL = NS_MM_EXEC["SceneModel"]
URI_EXEC_PRED_HAS_CONFIG = NS_MM_EXEC["has-config"]
URI_EXEC_PRED_PATH = NS_MM_EXEC["path"]
URI_EXEC_PRED_MODEL = NS_MM_EXEC["has-model"]
URI_EXEC_PRED_HAS_MODELLED_OBJ = NS_MM_EXEC["has-modelled-object"]
URI_EXEC_PRED_HAS_MODELLED_AGN = NS_MM_EXEC["has-modelled-agent"]
URI_EXEC_PRED_MODEL_ENTITY = NS_MM_EXEC["model-entity"]
URI_EXEC_PRED_HAS_MAPPING = NS_MM_EXEC["has-mapping"]
URI_EXEC_PRED_MAPS = NS_MM_EXEC["maps"]
URI_EXEC_PRED_HAS_KINEMATICS = NS_MM_EXEC["has-kinematics"]
